In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [32]:
import argparse

In [2]:
df = pd.read_csv('../data/heart_cleveland_upload.csv')

In [3]:
enc = OneHotEncoder()
categorical_features = [
    "sex",
    "cp",
    "fbs",
    "restecg",
    "exang",
    "slope",
    "ca",
    "thal",
]
numerical_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak",
]

In [4]:
categorical_df = df[categorical_features]
numerical_df = df[numerical_features]
enc.fit(categorical_df)

OneHotEncoder()

In [12]:
enc.categories_

[array([0, 1], dtype=int64),
 array([0, 1, 2, 3], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([0, 1, 2, 3], dtype=int64),
 array([0, 1, 2], dtype=int64)]

In [14]:
enc.transform(categorical_df).toarray().shape

(297, 23)

In [26]:
np.concatenate((numerical_df.to_numpy(), enc.transform(categorical_df).toarray()), axis=1)

array([[ 69., 160., 234., ...,   1.,   0.,   0.],
       [ 69., 140., 239., ...,   1.,   0.,   0.],
       [ 66., 150., 226., ...,   1.,   0.,   0.],
       ...,
       [ 35., 120., 198., ...,   0.,   0.,   1.],
       [ 35., 138., 183., ...,   1.,   0.,   0.],
       [ 35., 126., 282., ...,   0.,   0.,   1.]])

In [27]:
import pickle

In [28]:
with open('enc.pkl', 'wb') as f:
    pickle.dump(enc, f)

In [29]:
with open('enc.pkl', 'rb') as f:
    enc = pickle.load(f)

In [31]:
enc.categories_

[array([0, 1], dtype=int64),
 array([0, 1, 2, 3], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([0, 1, 2, 3], dtype=int64),
 array([0, 1, 2], dtype=int64)]

In [24]:
numerical_df.to_numpy().shaoe

AttributeError: 'numpy.ndarray' object has no attribute 'shaoe'

In [11]:
cur.toarray()

array([[0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [26]:
categorical_df = df[categorical_features]
enc.fit_transform(categorical_df)

<297x23 sparse matrix of type '<class 'numpy.float64'>'
	with 2376 stored elements in Compressed Sparse Row format>

In [ ]:
df[]

In [4]:
from marshmallow_dataclass import class_schema

In [3]:
import yaml